'use client';
import {useState} from 'react';import {useRouter} from 'next/navigation';
type Contact={id:string;name:string;title:string;email?:string|null;linkedin_url?:string|null;source_url:string;verification_status:string;confidence:number;evidence?:string|null;contact_type?:string|null};
type Props={application:{id:string;status:string;current_version:number;tailored_resume:string;cover_letter:string;recruiter_email:string;linkedin_message:string};job:{title:string;company:string;location?:string|null;source_url:string};versions:{version:number;created_at:string}[];contacts:Contact[]};
export default function ApplicationStudio({application:a,job,versions,contacts}:Props){const router=useRouter();const [resume,setResume]=useState(a.tailored_resume||'');const [letter,setLetter]=useState(a.cover_letter||'');const [email,setEmail]=useState(a.recruiter_email||'');const [linkedin,setLinkedin]=useState(a.linkedin_message||'');const [status,setStatus]=useState(a.status);const [busy,setBusy]=useState('');const [msg,setMsg]=useState('');
async function save(){setBusy('save');setMsg('');const r=await fetch(`/api/applications/${a.id}/save`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tailoredResume:resume,coverLetter:letter,recruiterEmail:email,linkedInMessage:linkedin})});const d=await r.json();setBusy('');setMsg(r.ok?`Saved as version ${d.version}`:d.error);if(r.ok)router.refresh();}
async function discover(){setBusy('contacts');setMsg('');const r=await fetch('/api/contacts/discover',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({applicationId:a.id})});const d=await r.json();setBusy('');setMsg(r.ok?`Found ${d.count} public-source contact candidate${d.count===1?'':'s'}. Review evidence before outreach.`:d.error);if(r.ok)router.refresh();}
async function personalize(id:string){setBusy('personalize');const r=await fetch(`/api/contacts/${id}/personalize`,{method:'POST'});const d=await r.json();setBusy('');if(r.ok){setEmail(d.email);setLinkedin(d.linkedin);setMsg('Outreach personalized in the editor. Review it, then save a new version.')}else setMsg(d.error);}
async function updateStatus(v:string){setStatus(v);const r=await fetch(`/api/applications/${a.id}/status`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({status:v})});if(!r.ok){const d=await r.json();setMsg(d.error)}else router.refresh();}
function txt(name:string,text:string){const blob=new Blob([text],{type:'text/plain;charset=utf-8'});const u=URL.createObjectURL(blob);const x=document.createElement('a');x.href=u;x.download=name;x.click();URL.revokeObjectURL(u)}
return <><section className="card section"><div className="topline"><div><span className="pill">Application Studio · v{a.current_version}</span><h1>{job.title}</h1><p className="lead">{job.company} · {job.location||'Location not listed'}</p></div><div><label>Status </label><select value={status} onChange={e=>updateStatus(e.target.value)}>{['interested','applying','applied','interview','follow_up','offer','rejected','closed'].map(x=><option key={x} value={x}>{x.replace('_',' ')}</option>)}</select></div></div><p><a href={job.source_url} target="_blank" rel="noreferrer">View original posting</a></p>{msg&&<p><b>{msg}</b></p>}</section>
<section className="card section"><div className="topline"><div><h2>Recruiter & Hiring Manager Intelligence</h2><p className="muted">Searches public web results and preserves source/evidence. A result is a research lead—not proof that a person owns this requisition.</p></div><button onClick={discover} disabled={!!busy}>{busy==='contacts'?'Researching…':contacts.length?'Refresh contacts':'Find contacts'}</button></div>{contacts.length?contacts.map(c=><div className="contact" key={c.id}><h3>{c.name} <span className="pill">{c.confidence}% evidence confidence</span></h3><p>{c.title} · {(c.contact_type||'unknown').replace('_',' ')}</p><p>{c.evidence}</p><p>{c.email&&<>Email: {c.email} · </>}{c.linkedin_url&&<><a href={c.linkedin_url} target="_blank" rel="noreferrer">LinkedIn</a> · </>}<a href={c.source_url} target="_blank" rel="noreferrer">Public source</a> · <button className="secondary" onClick={()=>personalize(c.id)} disabled={!!busy}>Personalize outreach</button></p><p className="muted">{c.verification_status==='strong_public_evidence'?'Strong public evidence; still verify role/requisition before contacting.':'Public-source lead; not independently verified.'}</p></div>):<p>No contact research saved yet.</p>}</section>
<Editor title="ATS Resume" value={resume} setValue={setResume} actions={<><a className="button secondary" href={`/api/applications/${a.id}/export?kind=resume&format=docx`}>DOCX</a><a className="button secondary" href={`/api/applications/${a.id}/export?kind=resume&format=pdf`}>PDF</a><button className="secondary" onClick={()=>txt(`${job.company}-${job.title}-resume.txt`,resume)}>TXT</button></>}/>
<Editor title="Cover Letter" value={letter} setValue={setLetter} actions={<><a className="button secondary" href={`/api/applications/${a.id}/export?kind=cover-letter&format=docx`}>DOCX</a><a className="button secondary" href={`/api/applications/${a.id}/export?kind=cover-letter&format=pdf`}>PDF</a><button className="secondary" onClick={()=>txt(`${job.company}-${job.title}-cover-letter.txt`,letter)}>TXT</button></>}/>
<Editor title="Recruiter / Hiring Manager Email" value={email} setValue={setEmail} actions={<button className="secondary" onClick={()=>txt(`${job.company}-${job.title}-outreach-email.txt`,email)}>Download</button>}/><Editor title="LinkedIn Message" value={linkedin} setValue={setLinkedin} actions={<button className="secondary" onClick={()=>txt(`${job.company}-${job.title}-linkedin.txt`,linkedin)}>Download</button>}/>
<section className="card section"><button onClick={save} disabled={!!busy}>{busy==='save'?'Saving…':'Save new version'}</button><h3>Version history</h3><p>{versions.length?versions.map(v=>`v${v.version} · ${new Date(v.created_at).toLocaleString()}`).join('  |  '):'No prior versions.'}</p><p className="muted">Review generated documents and contact research before submission or outreach. Stage 5 does not automatically send messages or submit applications.</p></section></>}
function Editor({title,value,setValue,actions}:{title:string;value:string;setValue:(x:string)=>void;actions:React.ReactNode}){return <section className="card section"><div className="topline"><h2>{title}</h2><div className="actions">{actions}</div></div><textarea className="artifact" value={value} onChange={e=>setValue(e.target.value)}/></section>}
